resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: feature/docker_build
    
trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
    - template: pdfgpt_template.yml