resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    
trigger:
- main

pool: 
  name: 'vmss-mdo-dev-eus'
  demands:
  - Agent.OS -equals Windows

stages:
    - template: pdfgpt_template.yml