parameters:
- name: environmentObjects
  type: object
  default:
    - environmentName: 'dev'
      regionAbrvs: ['eus']
      tags: 'latest'
- name: templateFileName
  type: string
  default: 'main'
- name: serviceName
  type: string
  default: 'pdfgptdemoext'
- name: containerRegistryServiceConnection
  type: string
  default: 'acrpdfgptdemoext'
- name: repositoryName
  type: string
  default: 'pdfgptdemoext'

stages:
- template: stages/bicep_docker_build_stage.yml@templates
  parameters:
    environmentObjects: ${{ parameters.environmentObjects }}
    templateFileName: ${{ parameters.templateFileName }}
    serviceName: ${{ parameters.serviceName }}

- ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
  - template: stages/docker_bicep_deploy_stage.yml@templates
    parameters:
      environmentObjects: ${{ parameters.environmentObjects }}
      templateFileName: ${{ parameters.templateFileName }}
      serviceName: ${{ parameters.serviceName }}
      containerRegistryServiceConnection: ${{ parameters.containerRegistryServiceConnection }}
      repositoryName: ${{ parameters.repositoryName }}
